"""updated wroskpace

Revision ID: 05f043a1310b
Revises: f486a9ea198a
Create Date: 2026-09-18 20:56:47.145251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f043a1310b'
down_revision: Union[str, Sequence[str], None] = 'f486a9ea198a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'user')
    op.drop_column('workspace', 'ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('ai', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('workspace', sa.Column('user', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
